import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

/** Font from Droguerías Colsubsidio–style sites (VTEX / e-commerce). */
const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${openSans.variable} flex min-h-screen flex-col font-sans antialiased`}>
        <AuthProvider>
          <main className="flex-1">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
